### ISSUE TITLE
Lots of errors during compilation

### ISSUE THREAD

**Issue by VanHoevenTR** [61bcdefg/Hikari-LLVM15#102]
I'm using Hikari-LLVM17 for NDK 26.3.11579264 but I got lots of errors during lib compilation

```
The ADBCallBack and ADBInit functions were not found
Unsupported Inline Assembly AntiDebugging Target: aarch64-none-linux-android22
Unsupported Inline Assembly AntiDebugging Target: armv7-none-linux-android22
Failed To Link PreCompiled AntiHooking IR From:C:/Users/(username)/Hikari/PrecompiledAntiHooking-aarch64-linux.bc
```

Can it be fixed?

**Comment by Naville** [comment]
it's not a bug, it's a warning telling you you didn't provide anti debug implementation. Which is pretty obvious if you spent 20secs reading through the documentation

**Comment by Naville** [comment]
I don't really understand the confusion. Probably it's your translation software's fault. You're supposed to implement the checks yourself, compile your implementations into LLVM IR and provide paths to those IRs

**Comment by Naville** [comment]
While we're at it. Due to platform nature, the entire "anti-debug" concept makes very little sense on Android, so probably not a good idea to waste too much time on it.

**Comment by 61bcdefg** [comment]
Just don’t use AntiDebugging
