### ISSUE TITLE
这是什么引入的？怎么关闭这个链接选项

### ISSUE THREAD

**Issue by codingsf** [61bcdefg/Hikari-LLVM15#103]
Unknown command line argument '-MMD'

**Comment by 61bcdefg** [comment]
与此项目无关

**Comment by codingsf** [comment]
我直接用llvm-17.0.6rel这个分支，编译成toolchain，然后xcode切换到这个toolchain。只要加上-mllvm的cflags，就报-mmd错误。不加-mllvm选项，编译就是正常的。 简单的看上去是-mllvm引入的-mmd啊。不过，还是感谢你们的无私分享。我自己想法解决下
