### ISSUE TITLE
Thoes编译arm64e ld warning:: found architecture 'arm64e.old', required architecture 'arm64e'

### ISSUE THREAD

**Issue by AbstractLee** [61bcdefg/Hikari-LLVM15#104]
环境：
Mac OS 14.5 Intel芯片
XCode 15.3
Hikari_LLVM17.0.6 
编译命令：
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" -DLLVM_ENABLE_PROJECTS=clang  -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_ZSTD=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DLLVM_CREATE_XCODE_TOOLCHAIN=ON  -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_BUILD_TOOLS=OFF -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON -DCMAKE_INSTALL_PREFIX="./install" ../llvm

Makefile:
iOS16.5SDK
export TARGET_CC = /usr/local/Toolchains/Hikari_LLVM17.0.6.xctoolchain/usr/bin/clang
export TARGET_CXX = /usr/local/Toolchains/Hikari_LLVM17.0.6.xctoolchain/usr/bin/clang++
export TARGET_LD = /usr/local/Toolchains/Hikari_LLVM17.0.6.xctoolchain/usr/bin/clang
CFLGAS = -fobjc-arc

make提示：
ld: warning: ignoring file '*****/Util.m.b639cb77.o': found architecture 'arm64e.old', required architecture 'arm64e'

make编译后的dylib拖到Hopper反汇编发现无代码，也不生效，请问大佬这是什么问题

**Comment by 61bcdefg** [comment]
构建新arm64e abi需要使用hanabi

**Comment by AbstractLee** [comment]
好的
