### ISSUE TITLE
failed to compile, Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by minhquangxx** [61bcdefg/Hikari-LLVM15#107]
i need help, thanks
**error**
```CMake Error at lib/Transforms/CMakeLists.txt:12 (add_subdirectory):
  The source directory

    /Users/quangblue/Hikari-LLVM15/llvm/lib/Transforms/Obfuscation

  does not contain a CMakeLists.txt file.
```
```
-- Performing Test HAVE_PTHREAD_AFFINITY -- failed to compile
-- Configuring incomplete, errors occurred!
```

```
1. git clone --branch apple-arm64e-upstream-next  https://github.com/61bcdefg/Hikari-LLVM15.git
2. cd Hikari-LLVM15
3. mkdir build
4. cd build
5. cmake -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_CREATE_XCODE_TOOLCHAIN=ON -DLLVM_ENABLE_PROJECTS="clang" -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_RUNTIMES="compiler-rt" -DLLVM_INCLUDE_TESTS=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 -DLLVM_INCLUDE_EXAMPLES=OFF ../llvm
```
<img width="1728" alt="image" src="https://github.com/61bcdefg/Hikari-LLVM15/assets/40761942/27454790-b742-4946-b174-011531f6cb5f">
<img width="1728" alt="image" src="https://github.com/61bcdefg/Hikari-LLVM15/assets/40761942/30dec963-c0c1-4dfc-b27a-277df15b70f7">

**Comment by 61bcdefg** [comment]
> 1. git clone --branch apple-arm64e-upstream-next  https://github.com/61bcdefg/Hikari-LLVM15.git


`git clone --recursive --branch apple-arm64e-upstream-next  https://github.com/61bcdefg/Hikari-LLVM15.git `

**Comment by minhquangxx** [comment]
> > 1. git clone --branch apple-arm64e-upstream-next  https://github.com/61bcdefg/Hikari-LLVM15.git
> 
> `git clone --recursive --branch apple-arm64e-upstream-next https://github.com/61bcdefg/Hikari-LLVM15.git `

i have new problem
after run ```sudo ninja install-xcode-toolchain```
error ```Undefined symbols for architecture arm64:
  "llvm::createObfuscationLegacyPass()", referenced from:
      __GLOBAL__sub_I_bugpoint.cpp in bugpoint.cpp.o
ld: symbol(s) not found for architecture arm64```
<img width="733" alt="image" src="https://github.com/61bcdefg/Hikari-LLVM15/assets/40761942/f262840c-9284-4a27-ab48-a9628d22fafa">

**Comment by 61bcdefg** [comment]
[https://github.com/61bcdefg/Hikari-LLVM15/commit/debec9ae4b5f49ed65f2f4923da5d7d148720223](https://github.com/61bcdefg/Hikari-LLVM15/commit/debec9ae4b5f49ed65f2f4923da5d7d148720223)

**Comment by minhquangxx** [comment]
thanks <3

**Comment by minhquangxx** [comment]
<img width="573" alt="image" src="https://github.com/61bcdefg/Hikari-LLVM15/assets/40761942/d8b61581-0340-47ef-a1c8-5ce4d949fef2">
Is this an error? it has been standing here for more than 2 hours, i use macbook m2 pro and xcode 15.2

**Comment by minhquangxx** [comment]
> [debec9a](https://github.com/61bcdefg/Hikari-LLVM15/commit/debec9ae4b5f49ed65f2f4923da5d7d148720223)

new error bro

<img width="1728" alt="image" src="https://github.com/61bcdefg/Hikari-LLVM15/assets/40761942/ef39ab48-a7b4-4a78-baf1-21f071391194">

**Comment by 61bcdefg** [comment]
This error has nothing to do with this project and is also present when building Apple's original source. So we cannot build `compiler-rt`, instead, copy the libraies from XcodeDefault.xctoolchain.
