### ISSUE TITLE
llvm-17.0.6rel 编译不了

### ISSUE THREAD

**Issue by netstu** [61bcdefg/Hikari-LLVM15#112]
一直提示 Enabling the legacy pass manager on the cmake level is no longer supported

编译参数
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_ARCHITECTURES=arm64 -DLLVM_ENABLE_PROJECTS=clang  -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" -DLLVM_ENABLE_ZSTD=OFF -DCMAKE_OSX_DEPLOYMENT_TARGET=12.0 -DLLVM_CREATE_XCODE_TOOLCHAIN=ON  -DLLVM_INCLUDE_TESTS=OFF -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_INCLUDE_UTILS=OFF -DLLVM_INCLUDE_BENCHMARKS=OFF -DLLVM_BUILD_TOOLS=OFF -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON -DCMAKE_INSTALL_PREFIX="./install" ../llvm

**Comment by 61bcdefg** [comment]
你是不是之前构建时传递了-DLLVM_ENABLE_NEW_PASS_MANAGER=OFF ？
这个选项默认是打开的
重新加上-DLLVM_ENABLE_NEW_PASS_MANAGER=ON
