### ISSUE TITLE
 请教一下关于___isPlatformVersionAtLeast 问题

### ISSUE THREAD

**Issue by LiuSky** [61bcdefg/Hikari-LLVM15#116]
Xcode15.4
Ollvm ：https://github.com/61bcdefg/Hikari-LLVM15/tree/llvm-16.0.0rel
其他的都是没问题，就是代码中如果有@available(iOS 13.0, *) 就会出现___isPlatformVersionAtLeast 的问题。
打扰下作者，想请问有什么解决方案吗？

**Comment by Naville** [comment]
CompilerRT

**Comment by 61bcdefg** [comment]
-DLLVM_ENABLE_PROJECTS="clang;compiler-rt"

或从XcodeDefault.xctoolchain里复制静态库

**Comment by LiuSky** [comment]
> -DLLVM_ENABLE_PROJECTS="clang;compiler-rt"
> 
> 或从XcodeDefault.xctoolchain里复制静态库
谢谢。
