### ISSUE TITLE
apple-arm64e-upstream-next  分支需要使用哪个版本的sdk？

### ISSUE THREAD

**Issue by fly8888** [61bcdefg/Hikari-LLVM15#120]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/swift/clang/include/stddef.h:103:10: fatal error: '__stddef_max_align_t.h' file not found
  103 | #include "__stddef_max_align_t.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from <built-in>:1:
/Users/code/theos/Prefix.pch:18:10: fatal error: could not build module 'Darwin'
   18 |         #import <AvailabilityVersions.h>

**尝试了iPhoneOS14.5.sdk,iPhoneOS15.6.sdk,iPhoneOS16.5.sdk,iPhoneOS17.4.sdk 都是报上述错误，有谁编译成功吗？**

**Comment by ugly-soul** [comment]
哈哈哈，放弃吧，他最后会给你说和本项目无关。目前可以暂时不考虑arm64e

**Comment by 61bcdefg** [comment]
> 哈哈哈，放弃吧，他最后会给你说和本项目无关。目前可以暂时不考虑arm64e

因为本身就没有关系

我觉得去theos官网看怎么关掉modules并不是一件十分困难的事，但是对于有的人来说可能很困难

**Comment by Naville** [comment]
> > 哈哈哈，放弃吧，他最后会给你说和本项目无关。目前可以暂时不考虑arm64e
> 
> 因为本身就没有关系
> 
> 我觉得去theos官网看怎么关掉modules并不是一件十分困难的事，但是对于有的人来说可能很困难

很符合我对UI仔的认知, 诶@ugly-soul 你怎么删评了

**Comment by ugly-soul** [comment]
> > > 哈哈哈，放弃吧，他最后会给你说和本项目无关。目前可以暂时不考虑arm64e
> > 
> > 
> > 因为本身就没有关系
> > 我觉得去theos官网看怎么关掉modules并不是一件十分困难的事，但是对于有的人来说可能很困难
> 
> 很符合我对UI仔的认知, 诶@ugly-soul 你怎么删评了

没怎么，有些途径试过了才询问的，既然不友好我何不删了....😔

**Comment by fly8888** [comment]
<img width="1219" alt="image" src="https://github.com/user-attachments/assets/6398ceed-85f1-4a59-bbd5-191086837986">

**Comment by fly8888** [comment]
`TWEAK_NAME = Test
Test_USE_MODULES = 0`

**Comment by fly8888** [comment]
> > > > 哈哈哈，放弃吧，他最后会给你说和本项目无关。目前可以暂时不考虑arm64e
> > > 
> > > 
> > > 因为本身就没有关系
> > > 我觉得去theos官网看怎么关掉modules并不是一件十分困难的事，但是对于有的人来说可能很困难
> > 
> > 
> > 很符合我对UI仔的认知, 诶@ugly-soul 你怎么删评了
> 
> 没怎么，有些途径试过了才询问的，既然不友好我何不删了....😔

解决了，看看吧。还得大佬提示，不然根本搞不懂原因。以为是sdk有问题。

**Comment by ugly-soul** [comment]
> > > > > 哈哈哈，放弃吧，他最后会给你说和本项目无关。目前可以暂时不考虑arm64e
> > > > 
> > > > 
> > > > 因为本身就没有关系
> > > > 我觉得去theos官网看怎么关掉modules并不是一件十分困难的事，但是对于有的人来说可能很困难
> > > 
> > > 
> > > 很符合我对UI仔的认知, 诶@ugly-soul 你怎么删评了
> > 
> > 
> > 没怎么，有些途径试过了才询问的，既然不友好我何不删了....😔
> 
> 解决了，看看吧。还得大佬提示，不然根本搞不懂原因。以为是sdk有问题。

嗯嗯
