### ISSUE TITLE
note: Using global toolchain override 'hikari.swift-llvm.16.0.0git'. (in target 'testeste2' from project 'testeste2')

### ISSUE THREAD

**Issue by fly8888** [61bcdefg/Hikari-LLVM15#125]
<img width="1171" alt="image" src="https://github.com/user-attachments/assets/ba826bcb-e6aa-49f1-8f9b-a824c89ffbb3">
<img width="1110" alt="image" src="https://github.com/user-attachments/assets/36a0e957-6296-44fd-b2f8-74ecf07118db">
<img width="807" alt="image" src="https://github.com/user-attachments/assets/935c0780-bae2-4a0c-bf42-f28184e74a45">

好奇怪，怎么会自动给替换为自带toolchain？啥情况？难道是权限带@的问题？

**Comment by 61bcdefg** [comment]
Swift-llvm不能混淆swift
