### ISSUE TITLE
Rearranging of basic blocks (question)

### ISSUE THREAD

**Issue by NewDwarf** [61bcdefg/Hikari-LLVM15#25]
How do you think, whether it is possible to implement basic block rearranging to harden the indirect branch obfuscation?
For example, we have such snippet of the obfuscated code
```
...
.text:0000000000001E90                 ADRL            X10, off_4988
.text:0000000000001E98                 CMP             W9, #0x10
.text:0000000000001E9C                 CSET            W8, CC
.text:0000000000001EA0                 LDR             X11, [X10,W8,UXTW#3]
.text:0000000000001EA4                 MOV             W8, W9
.text:0000000000001EA8                 BR              X11

.text:0000000000001EB0                 MOV             X12, SP
.text:0000000000001EB4                 REV             W11, W11
.text:0000000000001EB8                 STR             W11, [X12,W8,UXTW#2]
...
```
I ran such parts of the code (which has indirect branch BR X xx instruction) under uEmu in IDA Pro and noticed that execution just jumps on the "0000000000001EB0" address (there are many BR X xx replacements in the function being obfuscated). 
Above construction breaks decompilation but it can be easily binary patched by the "nop" instruction to make the code decompilable.
The idea is to rearrange the basic blocks to prevent easy prediction of jumping by the BR X xx instruction and make patching challenge more difficult.

**Comment by NeHyci** [comment]
Are you talking about bcf+cff+split? I think this can do what you're talking about, it already exists.

**Comment by Naville** [comment]
It can be done pretty easily

**Comment by NewDwarf** [comment]
> Are you talking about bcf+cff+split? I think this can do what you're talking about, it already exists.

Suppose, we have a such sequence 

```
Basic Block 1
BR X8 <- jump on the Basic Block 2

Basic Block 2
BR X8 <- jump on the Basic Block 3

Basic Block 3
BR X8 <- <- jump on the Basic Block 4

Basic Block 4
BR X8 <- <- jump on the Basic Block n
```

So, the sequence will be Basic Block 1 -> Basic Block 2 -> Basic Block 3 -> Basic Block 4 -> Basic Block n

The idea is to change this sequence on unpredictable manner like

Basic Block 1 -> Basic Block 4 -> Basic Block 2 -> Basic Block 3 -> Basic Block n

**Comment by NeHyci** [comment]
As the brief of the project states, this is a Hikari fork, and the functionality you describe is like the need to implement a new LLVM Pass, which is not in line with the introduction.
