### ISSUE TITLE
能否编译成so的形式

### ISSUE THREAD

**Issue by BRYNHILDRINTHEDARKNESS** [61bcdefg/Hikari-LLVM15#40]
能否改成此项目的形式：https://github.com/LeadroyaL/llvm-pass-tutorial
这样有一个好处，编译的时候直接将生成的so链接进去，就会方便得多。

**Comment by Naville** [comment]
LLVM是没有跨版本的API/ABI向前兼容的保证的, 你最终还是需要每个版本单独编译一份so

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
这个没关系的，一个llvm版本可以用很长时间

**Comment by Naville** [comment]
Apple的Clang是没有插件支持的, 并且至少Apple的Clang是不导出绝大多数符号的.

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
但我的生产环境是android，因为我要考虑便捷性，所以我会尽可能的将编译环境部署在linux，这样只需要加载一个hikari.so就可以完成混淆。

**Comment by Naville** [comment]
现在的这套构建系统应该是不行的, @NeHyci LLVM11+开始提供了一套新的可以做out-of-tree build的机制, 不再需要Patch LLVM源码, 可以切过去?

**Comment by NeHyci** [comment]
> 但我的生产环境是android，因为我要考虑便捷性，所以我会尽可能的将编译环境部署在linux，这样只需要加载一个hikari.so就可以完成混淆。

pass plugin能使用cl::opt吗？我记得好像是不行的吧，你说的那个仓库中-mllvm -sub这种参数有效吗？

**Comment by Naville** [comment]
我记得是能的, 你是不是构建系统有问题多链接了一份Support?
不过我们自己downstream也是static link

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> > 但我的生产环境是android，因为我要考虑便捷性，所以我会尽可能的将编译环境部署在linux，这样只需要加载一个hikari.so就可以完成混淆。
> 
> pass plugin能使用cl::opt吗？我记得好像是不行的吧，你说的那个仓库中-mllvm -sub这种参数有效吗？

是可以的 ，你可以看看代码，我现在正在用

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 现在的这套构建系统应该是不行的, @NeHyci LLVM11+开始提供了一套新的可以做out-of-tree build的机制, 不再需要Patch LLVM源码并且可以按需构建静态或者动态库, 可以切过去? CMake函数叫`add_llvm_pass_plugin` 需要的话可以Telegram之类的方式来问我也行

请问telegram是多少

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
@NeHyci 大佬 如果能改成编译动态库的方式，还请帮忙改改，拜托了
