### ISSUE TITLE
控制函数混淆无效

### ISSUE THREAD

**Issue by zhszy** [61bcdefg/Hikari-LLVM15#50]
你好，这边验证单个函数混淆，没有效果。能否解决一下？
xcode未配置混淆参数，代码中使用如下：
// c/c++
int foo() __attribute((__annotate__(("bcf_prob=100"))));
int foo() {
   return 2;
}
// Objc
extern void hikari_bcf_prob(uint32_t);
@implementation foo2 : NSObject
+(void)foo{
  hikari_bcf_prob(100);
  NSLog(@"FOOOO2");
}
@end

**Comment by 61bcdefg** [comment]
你得先把bcf开了才能控制范围

**Comment by zhszy** [comment]
开启bcf，会对别的函数也会产生效果。这边有个问题请教一下，如果只对某个函数进行操作，不影响其他函数的情况下，需要如何设置？

**Comment by 61bcdefg** [comment]
自己去看原项目wiki吧

**Comment by Naville** [comment]
您完全不看文档是吗
