### ISSUE TITLE
[FR] `lto` supports

### ISSUE THREAD

**Issue by yujincheng08** [61bcdefg/Hikari-LLVM15#54]
looks like this project does not support `lto`. (my [old ollvm compiler](https://github.com/bluesadi/Pluto-Obfuscator) works fine with `lto` enabled tho so I missed lto especially when I am going to statically link libc.a and `lto` can help delete unused functions)

**Comment by 61bcdefg** [comment]
> looks like this project does not support lto

What situation do you mean?

**Comment by yujincheng08** [comment]
> What situation do you mean?

When ever I enable lto, linker crashes.

**Comment by yujincheng08** [comment]
https://github.com/61bcdefg/Hikari-LLVM15-Core/commit/e13741f7751d730246324892a15a486be6e3eee4
