### ISSUE TITLE
[Help] Installation Guide.

### ISSUE THREAD

**Issue by ndlgiang** [61bcdefg/Hikari-LLVM15#56]
Dear authors,

I trust you are doing well.
I am a researcher on obfuscation binaries.
Coming here from your predecessor here https://github.com/HikariObfuscator/Hikari. I am struggling on how to compile and install your tool.

Could you please write a short `Compile & Install` guide for us?

Thank you,
Giang

**Comment by Naville** [comment]
Explain on how you are struggling

**Comment by ndlgiang** [comment]
Hi @Naville ,

From your repo https://github.com/HikariObfuscator/Hikari, I can follow `Compile & Install` page and execute cli command with `git clone` and `cmake` to build `llvm-obfuscator` and install via `ninja` installer.

However, there is no Installation guide in `Hikari-LLVM15` repo. There is no CMakelist.txt either. Could you please post a guide?
I have done following steps in `Hikari-LLVM15`:

```
0. Environment: Ubuntu 22.04 LTS
1. git clone -b llvm-15.0.2rel
2. stuck...
```

**Comment by Naville** [comment]
Commands should be almost the same
