### ISSUE TITLE
`constenc` is not compatible with LTO

### ISSUE THREAD

**Issue by yujincheng08** [61bcdefg/Hikari-LLVM15#59]
When enabling `constenc` and LTO, the linker crashes with:

```
ld.lld: error: Invalid record (Producer: 'LLVM16.0.0' Reader: 'LLVM 16.0.0')
```

I am trying to make a reproducible example.

**Comment by Naville** [comment]
.....What?

**Comment by yujincheng08** [comment]
@Naville @61bcdefg

Reproducible example:

```c++
namespace {
    bool do_check() {
        return true;
    }
    void test2(int client) {
        switch (client) {
            case 0: {
                static auto check = do_check();
            }
            case 1: {
            }
        }
    }
}

void test(int client) { test2(client); }
```

Compile with `-mllvm -enable-constenc -flto` will crash the linker.

**Comment by 61bcdefg** [comment]
try [https://github.com/61bcdefg/Hikari-LLVM15-Core/commit/66e19b5702cca5ff58336b87c90186d5bf6a54d3](https://github.com/61bcdefg/Hikari-LLVM15-Core/commit/66e19b5702cca5ff58336b87c90186d5bf6a54d3)

**Comment by Naville** [comment]
This is definitely not LTO related.

**Comment by yujincheng08** [comment]
@61bcdefg not working

**Comment by 61bcdefg** [comment]
That's kind of a weird question. After I reproduce this problem,  I  found it emited on the https://github.com/61bcdefg/Hikari-LLVM15/blob/llvm-16.0.0rel/llvm/lib/IR/Verifier.cpp#L647 of the mistakes, The Verifier considers the function to be a declaration, and the declared linkage must be external, which causes this error. I have yet to find out why the Verifier considers the function to be a declaration.

**Comment by pomelohan** [comment]
@yujincheng08 Tested on ndk-r25c-darwin with latest HEAD of 61bcdefg/Hikari-LLVM15-Core, with the source code and build command you provided, successfully built without crashing linker. Could you please make sure that whether the issue could be still reproduced with latest version 61bcdefg/Hikari-LLVM15-Core?

**Comment by 61bcdefg** [comment]
[https://github.com/61bcdefg/Hikari-LLVM15/tree/llvm-16.0.0rel](https://github.com/61bcdefg/Hikari-LLVM15/tree/llvm-16.0.0rel) or [https://github.com/61bcdefg/Hikari-LLVM15/tree/llvm-17.0.6rel](https://github.com/61bcdefg/Hikari-LLVM15/tree/llvm-17.0.6rel) should works now, and if you enable LTO, you need to pass `-Wl,-mllvm,-enable-xxx` to enable obfuscations.
