### ISSUE TITLE
Unsupported Configuration The Swift standard library from the toolchain cannot be used on devices.

### ISSUE THREAD

**Issue by 1153557859** [61bcdefg/Hikari-LLVM15#61]
Xcode 14.2  macos 12.6.2 
build Succeed

复制了build 的Hikari_Swift5.7.2-2023-04-10-a.xctoolchain 到 Xcode/Contents/Developer/Toolchains 目录下

运行时选择Hikari_Swift5.7.2  设备选择真机 提示 错误 

Unsupported Configuration 

The Swift standard library from the toolchain cannot be used on devices.  

Select a macOS or simulator run destination instead, or use a different toolchain that only provides the compiler.

**Comment by Naville** [comment]
Apple不让, 已知的问题, 需要Patch系统Toolchain或者Patch Xcode

**Comment by 1153557859** [comment]
archive 生成的 ipa 会生效吗 ？

**Comment by Naville** [comment]
不搞iOS开发, 不关心上架问题。 可以考虑这部分代码改成静态库然后用工具链单独编译再链接, 或者是Patch Xcode

**Comment by 1153557859** [comment]
不用于上架App Store 用于企业版本发布， Patch Xcode 有文档链接吗

**Comment by Naville** [comment]
不对外提供, 可以自己逆Xcode
