### ISSUE TITLE
开启-enable-constenc，运行项目 dispatch_once 函数Crash

### ISSUE THREAD

**Issue by zhszy** [61bcdefg/Hikari-LLVM15#63]
1、项目仅开启 -mllvm -enable-constenc
2、运行项目，dispatch_once函数crash

代码如下：
`+ (void)load {
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        [self registerHooks];
    });
}`

编译环境：
std::mt19937_64 seeded with current timestamp: 1681824889367
Initializing Hikari Core with Revision ID:e5a17492941da587c0430a6f3f2d3accb3ad7df6
Running Hikari On /Users/zhs/Desktop/zhs/Test1/Test1/ViewController.m
Running ConstantEncryption On -[ViewController viewDidLoad]
Running ConstantEncryption On +[ViewController load]
Running ConstantEncryption On _dispatch_once
Running ConstantEncryption On __22+[ViewController load]_block_invoke
Running ConstantEncryption On +[ViewController registerHooks]
Doing Post-Run Cleanup
Hikari Out
Spend Time: 0.0001149s

**Comment by 61bcdefg** [comment]
[https://github.com/61bcdefg/Hikari-LLVM15-Core/commit/3f43d2201e085d203bb7e2354f7cd2ae45ee596f](https://github.com/61bcdefg/Hikari-LLVM15-Core/commit/3f43d2201e085d203bb7e2354f7cd2ae45ee596f)
