### ISSUE TITLE
-bcf_onlyjunkasm 非 -O0情况下，编译异常

### ISSUE THREAD

**Issue by zhszy** [61bcdefg/Hikari-LLVM15#65]
1、设置-mllvm -enable-bcfobf -mllvm -bcf_onlyjunkasm=true ，非 -O0情况下，编译异常
2、设置-mllvm -enable-bcfobf -mllvm -bcf_prob=100 ，-os时 ida分析无效，需要开启-bcf_junkasm？

std::mt19937_64 seeded with current timestamp: 1683271051749
Initializing Hikari Core with Revision ID:b0bfa6a9ab29abf21a1a58fcc1312155672f7da4
clang-14: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Apple clang version 14.0.0 (https://github.com/61bcdefg/Hikari-LLVM15 16652acc47b8dedf0acbdb5a97e96b6535794f40)
Target: arm64-apple-macos13.0

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
@zhszy zhszy 你好，你是否是整合进ndk使用？

**Comment by zhszy** [comment]
> @zhszyzhszy 你好，你是不是整合进ndk使用？
基于项目swift-5.7.2分支，编译生成的toolchain

**Comment by BRYNHILDRINTHEDARKNESS** [comment]
> 

我以为是安卓平台

**Comment by 61bcdefg** [comment]
提供下源码或者IR

**Comment by zhszy** [comment]
> 提供下源码或者IR
源码：
`int main(int argc, const char * argv[]) {
    // insert code here...
    int a = 2;
    if(a == 0)
        return 1;
    else
        return 10;
    return 0;
}
`
1、使用Xcode新建了一个C项目，仅添加上面的代码
2、选择toolchain,设置-mllvm -enable-bcfobf -mllvm -bcf_prob=100  -mllvm -bcf_onlyjunkasm=true，无法编译

**Comment by 61bcdefg** [comment]
目前的pass流水线不适用于开启优化的情况
