### ISSUE TITLE
StringEncryption报错，麻烦看一下

### ISSUE THREAD

**Issue by renyankankan** [61bcdefg/Hikari-LLVM15#66]
1.	<eof> parser at end of file
2.	[Optimizer](url)
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  clang-14                 0x0000000105ee0ec6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 43
1  clang-14                 0x0000000105ee0997 llvm::sys::CleanupOnSignal(unsigned long) + 180
2  clang-14                 0x0000000105e595b9 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) + 97
3  clang-14                 0x0000000105e5979a CrashRecoverySignalHandler(int) + 135
4  libsystem_platform.dylib 0x00007ff81d29d5ed _sigtramp + 29
5  libsystem_platform.dylib 0x00007ff7bb5bd201 _sigtramp + 18446744072068660273
6  clang-14                 0x0000000105941ac4 llvm::ConstantDataSequential::getElementAsConstant(unsigned int) const + 60
7  clang-14                 0x00000001069f1569 llvm::StringEncryption::HandleDecryptionBlock(llvm::BasicBlock*, llvm::BasicBlock*, std::__1::map<llvm::GlobalVariable*, std::__1::pair<llvm::Constant*, llvm::GlobalVariable*>, std::__1::less<llvm::GlobalVariable*>, std::__1::allocator<std::__1::pair<llvm::GlobalVariable* const, std::__1::pair<llvm::Constant*, llvm::GlobalVariable*> > > >&) + 877
8  clang-14                 0x00000001069f064b llvm::StringEncryption::HandleFunction(llvm::Function*) + 15493
9  clang-14                 0x00000001069ec986 llvm::StringEncryption::runOnModule(llvm::Module&) + 494
10 clang-14                 0x00000001069f6f1e llvm::Obfuscation::runOnModule(llvm::Module&) + 578
11 clang-14                 0x00000001069f6b03 llvm::ObfuscationPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 37
12 clang-14                 0x00000001069c6c04 llvm::detail::PassModel<llvm::Module, llvm::ObfuscationPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 18
13 clang-14                 0x00000001059e5e7c llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 398
14 clang-14                 0x00000001060e502a (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) + 6176
15 clang-14                 0x00000001060e14f0 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) + 1412
16 clang-14                 0x0000000106327cc2 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 1544
17 clang-14                 0x000000010702b1c1 clang::ParseAST(clang::Sema&, bool, bool) + 518
18 clang-14                 0x000000010653969d clang::FrontendAction::Execute() + 75
19 clang-14                 0x00000001064e9921 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 467
20 clang-14                 0x0000000106590924 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 516
21 clang-14                 0x0000000104942aec cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 1888
22 clang-14                 0x0000000104941c28 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) + 256
23 clang-14                 0x0000000106401ec5 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const::$_1>(long) + 23
24 clang-14                 0x0000000105e59536 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 226
25 clang-14                 0x0000000106401a0a clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*, bool*) const + 230
26 clang-14                 0x00000001063e26af clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const + 535
27 clang-14                 0x00000001063e27b7 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) const + 95
28 clang-14                 0x00000001063eea09 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*> >&) + 213
29 clang-14                 0x0000000104941753 main + 6854
30 dyld                     0x00007ff81cf1641f start + 1903
clang-14: error: clang frontend command failed with exit code 139 (use -v to see invocation)
clang version 14.0.0 (https://github.com/61bcdefg/Hikari-LLVM15.git 16652acc47b8dedf0acbdb5a97e96b6535794f40)
Target: x86_64-apple-ios6.0-simulator
Thread model: posix
InstalledDir: /Users/idea02/Library/Developer/Toolchains/Hikari-LLVM14.0.0git.xctoolchain/usr/bin
clang-14: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: [/var/folders/ky/yz4mj4lx2556b9hq545k2mk80000gn/T/YLibfbxsdk-3bc0ca.cpp]([url](url))
clang-14: note: diagnostic msg: /var/folders/ky/yz4mj4lx2556b9hq545k2mk80000gn/T/YLibfbxsdk-3bc0ca.sh
clang-14: note: diagnostic msg: Crash backtrace is located in
clang-14: note: diagnostic msg: /Users/idea02/Library/Logs/DiagnosticReports/clang-14_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang-14: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang-14: note: diagnostic msg: 

[归档.zip](https://github.com/61bcdefg/Hikari-LLVM15/files/11404819/default.zip)

**Comment by Naville** [comment]
他这个CrashLog感觉是读字符串的时候越界了? 但我也无法复现也看不出代码哪里有问题

**Comment by renyankankan** [comment]
> 复现不了

我们这边编译是必现，还需要提供什么信息吗？

**Comment by Naville** [comment]
插个无关的, 鉴于你这个项目是C++的。 那些基于C++ MetaProgramming的字符串加密比用这项目里的实现可能效果还好一点

**Comment by Naville** [comment]
我的建议是你复现的话可以先用clang -S -emit-llvm不开混淆, 然后单独用opt +混淆参数复现. 直接给源码的话不一定能生成完全一样的IR
