### ISSUE TITLE
FunctionCallObfuscate 设置后，运行Crash

### ISSUE THREAD

**Issue by zhszy** [61bcdefg/Hikari-LLVM15#67]
源码：
`int main ()`
`{`
` char str[50];`
`   unsigned long len;`
`   strcpy(str, "This is runoob.com");`
`   len = strlen(str);`
`   printf("|%s| 的长度是 |%lu|\n", str, len);`
`   return(0);`
`}`
SymbolConfig配置：{"strlen":"hello"}

**Comment by Naville** [comment]
fco是一个完全不建议开启的Pass, 有海量已知且难以修复的问题

**Comment by Naville** [comment]
不对, 我看错了。 我说的有问题不建议开启的是FunctionWrapper。
回到你的问题, 为什么你的strlen配置的是hello?

**Comment by zhszy** [comment]
> 

这个对应的值需要设置成strlen，如{"strlen":"strlen"}？

**Comment by Naville** [comment]
https://github.com/HikariObfuscator/Hikari/wiki/FunctionCallObfuscate

```
For example {"AAAA":"BBBB"} means the pass should replace a call to function AAAA with a call to the result of void* handle=dlopen(NULL,FLAGS);dlsym(handle,"BBBB")
By default configuration is loaded from ~/Hikari/SymbolConfig.json
```

你的strlen的符号叫hello是吗

**Comment by zhszy** [comment]
对不住哦，应该是缺少了#include <dlfcn.h>

**Comment by Naville** [comment]
???
