### ISSUE TITLE
Unknown command line argument '-enable-allobf'.  Try: 'clang (LLVM option parsing)

### ISSUE THREAD

**Issue by 275919229** [61bcdefg/Hikari-LLVM15#68]
你好，16.0.0 编译成功后。在other c Flags 添加 -mllvm -enable-allobf时报错. 还烦请看一下

1.xctoolchain编译成功
git clone --recursive -b llvm-16.0.0rel https://github.com/61bcdefg/Hikari-LLVM15.git Hikari && cd Hikari && git submodule update --remote --recursive && mkdir Build && cd Build && cmake -G "Ninja" -DLLDB_CODESIGN_IDENTITY='' -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_APPEND_VC_REV=on -DLLVM_CREATE_XCODE_TOOLCHAIN=on -DCMAKE_INSTALL_PREFIX=~/Library/Developer/ ../llvm && ninja && ninja install-xcode-toolchain && git clone https://github.com/HikariObfuscator/Resources.git ~/Hikari/llvm && rsync -a --ignore-existing /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/ ~/Library/Developer/Toolchains/Hikari_LLVM16.0.0.xctoolchain/ && rm ~/Library/Developer/Toolchains/LLVM16.0.0.xctoolchain/ToolchainInfo.plist

2.demo 编译,报错
clang (LLVM option parsing): Unknown command line argument '-enable-allobf'.  Try: 'clang (LLVM option parsing) --help'
clang (LLVM option parsing): Did you mean '--enable-newgvn'?
/Users/abcd/Library/Developer/Xcode/DerivedData/TT34-cqsaasdggigqjdeksrebqgaovnoe/Build/Intermediates.noindex/TT34.build/Debug-iphonesimulator/TT34.build/Objects-normal/x86_64/ViewController.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'TT34' from project 'TT34')
Command CompileC failed with a nonzero exit code

**Comment by 61bcdefg** [comment]
有没有可能，你不切换的话toolchain还是原版xcode的toolchain

**Comment by 275919229** [comment]
因为我切换到原版，就可以正常编译
切换到这个编译的版本就不行
<img width="461" alt="image" src="https://github.com/61bcdefg/Hikari-LLVM15/assets/18477827/ce37c692-7162-4208-8c23-1d9ab8e090c9">

**Comment by 61bcdefg** [comment]
这个issue没有什么意义

**Comment by Naville** [comment]
血压开始高了

**Comment by DaemonSong** [comment]
> 有没有可能，你不切换的话toolchain还是原版xcode的toolchain

你好，我遇到了同样的问题，请问你说的切换，不就是在Xcode菜单选择Toolchains，然后选中我们编译好的吗？这样操作以后，还是不识别flags呢，请问是哪里出错了，

**Comment by DaemonSong** [comment]
> @DaemonSong
> 
> * 确认Toolchain里的Clang确实带上了混淆代码(`strings clang二进制文件路径|grep 任意一个混淆参数的名称`)
> * 展开Xcode实际编译的Log, 确认用的是Toolchain里的Clang


1. 确认自己编译生成的Clang是带了混淆pass的
2. 编译log部分截图：
![CleanShot 2023-06-28 at 11 11 38@2x](https://github.com/61bcdefg/Hikari-LLVM15/assets/136695955/7ecaa9de-6089-49a9-a4b4-38bcc99b548b)
报错信息还是不识别flags，使用的Xcode版本为14.3.1，编译的分支为llvm-swift-5.8-RELEASE

**Comment by DaemonSong** [comment]
> @DaemonSong
> 
> * 确认Toolchain里的Clang确实带上了混淆代码(`strings clang二进制文件路径|grep 任意一个混淆参数的名称`)
> * 展开Xcode实际编译的Log, 确认用的是Toolchain里的Clang

另，有其他实现思路，是否能指点一二？目前完全替换Clang的做法个人认为不太可取，Apple本身会做很多优化。请问有没有方案能这样实现：
1. 使用原始Apple Clang编译出 IR
2. 调用自己的混淆库去混淆 IR
3. 最好调用Apple Clang编译混淆之后的 IR
这样的话，既能保留Apple原有的代码优化，又能添加自己的混淆实现。

**Comment by Naville** [comment]
我印象里Apple的编译器侧没有特别的运行时性能优化? 
另外跨编译器版本容易出各种奇怪的问题, 建议老老实实基于Apple的LLVM fork

**Comment by DaemonSong** [comment]
> 我印象里Apple的编译器侧没有特别的运行时性能优化?
> 另外跨编译器版本容易出各种奇怪的问题, 建议老老实实基于Apple的LLVM fork

麻烦再问下，怎么根据Xcode版本找到对应的Apple LLVM(https://github.com/apple/llvm-project)的分支？
比如目前我使用的是：
Apple clang version 14.0.3 (clang-1403.0.22.14.1)

在映射关系中只能看到这么多：
![CleanShot 2023-06-28 at 14 16 11@2x](https://github.com/61bcdefg/Hikari-LLVM15/assets/136695955/ed2aaefd-db4f-4b8a-a686-72ad04f22e80)

**Comment by 61bcdefg** [comment]
@DaemonSong 你能把你编译的toolchain里的clang上传到这里吗

**Comment by DaemonSong** [comment]
> @DaemonSong 你能把你编译的toolchain里的clang上传到这里吗

刚重新编译了一下，clang已经上传了，大小受限，分卷压缩了：
[clang001.zip](https://github.com/61bcdefg/Hikari-LLVM15/files/11891791/clang001.zip)
[clang002.zip](https://github.com/61bcdefg/Hikari-LLVM15/files/11891794/clang002.zip)
[clang003.zip](https://github.com/61bcdefg/Hikari-LLVM15/files/11891797/clang003.zip)
[clang004.zip](https://github.com/61bcdefg/Hikari-LLVM15/files/11891798/clang004.zip)

bao c 依然是不识别指令：
![CleanShot 2023-06-28 at 16 08 00@2x](https://github.com/61bcdefg/Hikari-LLVM15/assets/136695955/e0834ace-bb4e-4873-b217-14f7e257e820)
添加的flags指令：

![CleanShot 2023-06-28 at 16 09 29@2x](https://github.com/61bcdefg/Hikari-LLVM15/assets/136695955/388fa473-c230-45b7-9a2d-e7af37d49d7f)

**Comment by 61bcdefg** [comment]
我应该说什么
<img width="499" alt="截屏2023-06-28 16 31 51" src="https://github.com/61bcdefg/Hikari-LLVM15/assets/78954867/ce8de3ee-09f1-4356-b658-f773da4c9b39">

**Comment by DaemonSong** [comment]
> 我应该说什么
> 你把clang换成了Xcode内置工具链的原版clang，然后问我为什么混淆不了
> <img alt="截屏2023-06-28 16 31 51" width="499" src="https://user-images.githubusercontent.com/78954867/249404797-ce8de3ee-09f1-4356-b658-f773da4c9b39.png">

抱歉，是我哪一步操作错了吗？cmake编译之后直接用的...是cmake的时候没有添加-DLLVM_ENABLE_PROJECTS="clang"参数吗？

目前的指令：
cmake -G "Ninja" -DLLDB_CODESIGN_IDENTITY='' -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_APPEND_VC_REV=on -DLLVM_CREATE_XCODE_TOOLCHAIN=on -DCMAKE_INSTALL_PREFIX=~/Library/Developer/ ../llvm

**Comment by DaemonSong** [comment]
> 我应该说什么
> 你把clang换成了Xcode内置工具链的原版clang，然后问我为什么混淆不了
> <img alt="截屏2023-06-28 16 31 51" width="499" src="https://user-images.githubusercontent.com/78954867/249404797-ce8de3ee-09f1-4356-b658-f773da4c9b39.png">

抱歉，耽误了这么久，添加了clang参数之后在简单demo没问题。
但是在实际项目中，代码中遇到@available的时候，会报错_isPlatformVersionAtLeast， @Naville 提示是没链接clangRT，请问这个问题怎么解决？再次感谢。

**Comment by Naville** [comment]
> 我应该说什么 你把clang换成了Xcode内置工具链的原版clang，然后问我为什么混淆不了

如果我没记错的话我当时写的那个rsync脚本有问题, 后续专业版本的Hikari已经不使用rsync了. 现代版本的Xcode有了更好的External Toolchain支持

> 但是在实际项目中，代码中遇到@available的时候，会报错_isPlatformVersionAtLeast

我觉得提示已经足够明显了

**Comment by Naville** [comment]
如果你还是不太理解的话, 那玩意的正确名称叫compiler-rt, clangRT只是落地到磁盘上的文件名

**Comment by DaemonSong** [comment]
> > 我应该说什么 你把clang换成了Xcode内置工具链的原版clang，然后问我为什么混淆不了
> 
> 如果我没记错的话我当时写的那个rsync脚本有问题, 后续专业版本的Hikari已经不使用rsync了. 现代版本的Xcode有了更好的External Toolchain支持
> 
> > 但是在实际项目中，代码中遇到@available的时候，会报错_isPlatformVersionAtLeast
> 
> 我觉得提示已经足够明显了

好的，感谢解惑
