### ISSUE TITLE
编译"install-xcode-toolchain"时提示not contain a target named 'all' (Xcode13.4.1)

### ISSUE THREAD

**Issue by kxl2005** [61bcdefg/Hikari-LLVM15#70]
xcodebuild: error: The project 'LLVM.xcodeproj' does not contain a target named 'all'.
make: *** .../build/tools/xcode-toolchain/CMakeFiles/build-xcode-toolchain] Error 65
Command /bin/sh failed with exit code 2

**Comment by Naville** [comment]
大伙一般不用Xcode

**Comment by 61bcdefg** [comment]
构建llvm的方式不对
