### ISSUE TITLE
应该如何编译使用呢？

### ISSUE THREAD

**Issue by w296488320** [61bcdefg/Hikari-LLVM15#73]
切换到15.x分支发现 编译报错 。
PS F:\Hikari-LLVM15\Build> cmake -G "Ninja" -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_APPEND_VC_REV=on ../../Hikari-LLVM15
CMake Error: The source directory "F:/Hikari-LLVM15" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.   

修改以后提示：
....
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-w64-windows-gnu
-- LLVM default target triple: x86_64-w64-windows-gnu
CMake Error at CMakeLists.txt:813 (message):
  Enabling the legacy pass manager on the cmake level is no longer supported.

-- Configuring incomplete, errors occurred!
See also "F:/Hikari-LLVM15/build/CMakeFiles/CMakeOutput.log".
See also "F:/Hikari-LLVM15/build/CMakeFiles/CMakeError.log".

**Comment by 61bcdefg** [comment]
> PS F:\Hikari-LLVM15\Build> cmake -G "Ninja" -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_APPEND_VC_REV=on ../llvm
>

**Comment by w296488320** [comment]
PS F:\Hikari-LLVM15\Build> cmake -G "Ninja" -DCMAKE_BUILD_TYPE=MinSizeRel -DLLVM_APPEND_VC_REV=on ../llvm
-- bolt project is disabled
-- clang project is enabled
-- clang-tools-extra project is enabled
-- compiler-rt project is disabled
-- cross-project-tests project is disabled
-- libc project is disabled
-- libclc project is disabled
-- libcxx project is disabled
-- libcxxabi project is disabled
-- libunwind project is disabled
-- lld project is disabled
-- lldb project is disabled
-- mlir project is disabled
-- openmp project is disabled
-- polly project is disabled
-- pstl project is disabled
-- flang project is disabled
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR)
-- Could NOT find Backtrace (missing: Backtrace_LIBRARY Backtrace_INCLUDE_DIR)
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Ninja version: 1.10.2
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH)
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-w64-windows-gnu
-- LLVM default target triple: x86_64-w64-windows-gnu
CMake Error at CMakeLists.txt:813 (message):
  Enabling the legacy pass manager on the cmake level is no longer supported.


-- Configuring incomplete, errors occurred!
See also "F:/Hikari-LLVM15/build/CMakeFiles/CMakeOutput.log".
See also "F:/Hikari-LLVM15/build/CMakeFiles/CMakeError.log".
PS F:\Hikari-LLVM15\Build>

具体报错原因：
File F:/Hikari-LLVM15/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <stdio.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef __GLIBC__
  return ((int*)(&__GLIBC__))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Determining if the proc_pid_rusage exist failed with the following output:
Change Dir: F:/Hikari-LLVM15/build/CMakeFiles/CMakeTmp

Run Build Command(s):D:/AndroidStudio/SDK/cmake/3.22.1/bin/ninja.exe cmTC_6300d && [1/2] Building C object CMakeFiles/cmTC_6300d.dir/CheckSymbolExists.c.obj

FAILED: CMakeFiles/cmTC_6300d.dir/CheckSymbolExists.c.obj 

E:\mingw64\bin\gcc.exe    -o CMakeFiles/cmTC_6300d.dir/CheckSymbolExists.c.obj -c F:/Hikari-LLVM15/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c

F:/Hikari-LLVM15/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:2:10: fatal error: libproc.h: No such file or directory
    2 | #include <libproc.h>
      |          ^~~~~~~~~~~
compilation terminated.

ninja: build stopped: subcommand failed.



File F:/Hikari-LLVM15/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <libproc.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef proc_pid_rusage
  return ((int*)(&proc_pid_rusage))[argc];
#else
  (void)argc;
  return 0;
#endif
}
Performing C++ SOURCE FILE Test SUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG failed with the following output:
Change Dir: F:/Hikari-LLVM15/build/CMakeFiles/CMakeTmp

Run Build Command(s):D:/AndroidStudio/SDK/cmake/3.22.1/bin/ninja.exe cmTC_0afc9 && [1/2] Building CXX object CMakeFiles/cmTC_0afc9.dir/src.cxx.obj

FAILED: CMakeFiles/cmTC_0afc9.dir/src.cxx.obj 

E:\mingw64\bin\c++.exe -DSUPPORTS_GNU_ZERO_VARIADIC_MACRO_ARGUMENTS_FLAG  -Wgnu-zero-variadic-macro-arguments -std=c++14 -o CMakeFiles/cmTC_0afc9.dir/src.cxx.obj -c F:/Hikari-LLVM15/build/CMakeFiles/CMakeTmp/src.cxx

c++.exe: error: unrecognized command-line option '-Wgnu-zero-variadic-macro-arguments'
ninja: build stopped: subcommand failed.



Source file was:
int main() { return 0; }

**Comment by 61bcdefg** [comment]
我不太清楚windows上构建llvm是什么情况，所以我大概帮不了你

**Comment by w296488320** [comment]
明白，再次感谢，我研究一下。

**Comment by Naville** [comment]
> CMake Error at CMakeLists.txt:813 (message):
Enabling the legacy pass manager on the cmake level is no longer supported.

**Comment by w296488320** [comment]
刚刚在win编译成功了Hikari，请问Hikari有llvm 14x的么？我想替换ndk 25的版本 。

**Comment by 61bcdefg** [comment]
> 刚刚在win编译成功了Hikari，请问Hikari有llvm 14x的么？我想替换ndk 25的版本 。

没有原版llvm14.x的，你得自己移植，怎么移植可以看swift llvm 5.7那个branch里的commit

**Comment by w296488320** [comment]
尝试移植了一下没搞定 哎 ，老板有兴趣移植17x的版本么？ 我看了一下NDK的26版本，用的是llvm 17x ，再次感谢回复 。

**Comment by 61bcdefg** [comment]
17现在还没有release，等release了会考虑

**Comment by w296488320** [comment]
另外再次感谢您能回复 ，再次感谢 。

**Comment by w296488320** [comment]
白费，他们那个 frida 我没样本 ，根本没任何特征，我读取本地文件和内存text和got表，指令累加 做对比 ，没用 ，没任何特征 、我先前把ptrace 去attach自己 ，然后开一条线程 自己反复读取status ，检测attach pid ，然后再用读取的这个pid读取进程名 看看和我fork出来的进程名是否相等 ， 都检测不出来 ，他那个内核版本的frida 不知道啥原理 ，被搞得头疼 。

**Comment by w296488320** [comment]
win 的么？ 有的话想白飘一份哈哈哈哈

**Comment by w296488320** [comment]
v 296488320，我准备在hunter上用哇哈哈 。

**Comment by CodePwn2021** [comment]
@YoungJack-Y 啊哈哈，大佬我也想白嫖一份可以吗？Telegram@Oxygen_X19
