### ISSUE TITLE
可以插题问一下关于Hanabi具体是怎么使用的吗？

### ISSUE THREAD

**Issue by GoDaie** [61bcdefg/Hikari-LLVM15#74]
Hanabi那边已经归档没法发问题了。。。网上找了一圈儿也没找到说用法的。

**Comment by 61bcdefg** [comment]
我觉得这个问题没有讨论的价值

**Comment by 61bcdefg** [comment]
你只需要从release里下载然后根据readme里的步骤进行注入，然后像使用toolchain一样关掉优化，在cflags/swift flags里添加混淆选项

**Comment by GoDaie** [comment]
`sudo optool install -c load -p @executable_path/libLLVMHanabi.dylib -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang`

`sudo optool install -c load -p @executable_path/libLLVMHanabi.dylib -t /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend`

`sudo codesign -fs - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang`

`sudo codesign -fs - /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend`
意思是到这一步算是注入完成了吗？ 
< 3

-mllvm -enable-bcfobf 
-mllvm -enable-cffobf 
-mllvm -enable-splitobf 
-mllvm -enable-subobf
-mllvm -enable-acdobf 
-mllvm -enable-indibran 
-mllvm -enable-strcry 
-mllvm -enable-funcwra 
然后根据需要在Flags里面添加这些混淆选项就行了么，确实是一个很没有技术性的问题，刚接触iOS混淆举步维艰，要学习的东西还很多 - -
感谢能抽空回复我，非常感谢！
