### ISSUE TITLE
如何指定某个文件混淆或者不混淆呢？

### ISSUE THREAD

**Issue by LarissaLycoris** [61bcdefg/Hikari-LLVM15#75]
如何指定某个文件混淆或者不混淆呢？或者整个文件夹不混淆，亦或者只有这个文件夹或文件可以混淆 其他不混淆

**Comment by 61bcdefg** [comment]
Build Phases - Compiler Flags

**Comment by LarissaLycoris** [comment]
> Build Phases - Compiler Flags

这是设置混淆类型吧，我是想让某个文件 比如某个.mm文件 整个文件里面的内容都不混淆，其他的.mm正常混淆

**Comment by 61bcdefg** [comment]
这是个很蠢的问题

**Comment by Naville** [comment]
文档看不懂吗 构建系统整不明白吗

**Comment by LarissaLycoris** [comment]
> 这是个很愚蠢的问题

已经解决了 感谢回复，想问一下编译混淆文件一般 是编译Debug版本还是Release版本会比较好。我在某个论坛看到说hikari本身就不推荐用release版本。但是我在相关文档内没有看到这个说明，所以想咨询一下哪个会好些

**Comment by Naville** [comment]
> 我在某个论坛看到说hikari本身就不推荐用release版本。但是我在相关文档内没有看到这个说明，所以想咨询一下哪个会好些
?

**Comment by androiddisk** [comment]
> > 这是个很愚蠢的问题
> 
> 已经解决了 感谢回复，想问一下编译混淆文件一般 是编译Debug版本还是Release版本会比较好。我在某个论坛看到说hikari本身就不推荐用release版本。但是我在相关文档内没有看到这个说明，所以想咨询一下哪个会好些

大佬请问如何解决的哇

**Comment by androiddisk** [comment]
https://github.com/61bcdefg/Hikari-LLVM15?tab=readme-ov-file#cc-functions

这里的方式指定混淆不么？ 只有c/c++ 请问rust呢
