### ISSUE TITLE
IntegerTyID on the Apple clang 15 is different from the Swift llvm

### ISSUE THREAD

**Issue by 61bcdefg** [61bcdefg/Hikari-LLVM15#76]
在Apple clang 15上IntegerTyID变成了14，而不是正常的[13](https://github.com/apple/llvm-project/blob/070d3866709b23cb3a978c84966a50b5184ca657/llvm/include/llvm/IR/Type.h#L71)，使Hanabi上一些关于类型的判断函数的返回值是错误的，可能会导致出现问题

**Comment by Naville** [comment]
感觉可以用AppleClang的源码编译插件
