### ISSUE TITLE
LLVM 17

### ISSUE THREAD

**Issue by Yehh22** [61bcdefg/Hikari-LLVM15#77]
Can you add support for LLVM 17.0.2? I want to use Hikari with Android NDK 26.0.10792818. There is no NDK version that uses LLVM 15 or 16. Previous version 25.2.9519653 was using 14.0.5

**Comment by Naville** [comment]
16 and 15 should be mostly the same w.r.t. passes at this level

**Comment by JasonKhew96** [comment]
you can use NDK 26 with LLVM 16, but you need to `ln` the lib folder from 16 to 17 (on Linux), it will yield ld error when compiling.

**Comment by Naville** [comment]
> you can use NDK 26 with LLVM 16, but you need to `ln` the lib folder from 16 to 17 (on Linux), it will yield ld error when compiling.

wrong approach. don't do it

**Comment by RabahX** [comment]
> [my_patch.zip](https://github.com/61bcdefg/Hikari-LLVM15/files/13206967/my_patch.zip)

can you send me your obfuscated NDK with hikoru r26b

**Comment by 61bcdefg** [comment]
[https://github.com/61bcdefg/Hikari-LLVM15/tree/llvm-17.0.6rel](https://github.com/61bcdefg/Hikari-LLVM15/tree/llvm-17.0.6rel)
