### ISSUE TITLE
Xcode15 swifi-frontend have a crash(use libLLVMHanabi.dylib、libLLVMHanabiDeps.dylib)

### ISSUE THREAD

**Issue by xiaoxu1234** [61bcdefg/Hikari-LLVM15#78]
![截屏2023-09-26 16 21 29](https://github.com/61bcdefg/Hikari-LLVM15/assets/13639683/cfa7147d-28c5-469c-ba29-1ec6b3368de0)

**Comment by Naville** [comment]
这不是Swift上流的Bug， 别在那边拉屎了

**Comment by Naville** [comment]
(+https://github.com/61bcdefg/Hikari-LLVM15/issues/77#issuecomment-1733438173)
也没人有兴趣维护这个项目

**Comment by xiaoxu1234** [comment]
> (+[#77 (comment)](https://github.com/61bcdefg/Hikari-LLVM15/issues/77#issuecomment-1733438173))
> 也没人有兴趣维护这个项目

i also try Hanabi For Xcode15, you means libLLVMHanabi.dylib、libLLVMHanabiDeps.dylib have bugs?

**Comment by Naville** [comment]
是的

**Comment by Naville** [comment]
另外这几个都不是苹果或者LLVM上流的Bug, 别去拉屎给人家添麻烦了

**Comment by xiaoxu1234** [comment]
ok，Thanks。

**Comment by 61bcdefg** [comment]
[https://github.com/61bcdefg/Hikari-LLVM15#swift%E6%B7%B7%E6%B7%86%E6%94%AF%E6%8C%81](https://github.com/61bcdefg/Hikari-LLVM15#swift%E6%B7%B7%E6%B7%86%E6%94%AF%E6%8C%81)
