### ISSUE TITLE
Hanabi 兼容性问题？

### ISSUE THREAD

**Issue by Sfvgtg** [61bcdefg/Hikari-LLVM15#79]
您好，使用的Hanabi，flutter项目，还有OC&Swift语言，未设置flags时正常使用，也提示Applying Apple Clang Hooks...(注入成功)
，开启以后(任意一个flag),混淆pass正常运行，bcf cff sub等正常打印Running...  但是会报以下错误：

fatal error: module 'WBRouter' not found
@import WBRouter;
 ~~~~~~~^~~~~~~~
1 error generated.

查阅资料需要flutter clean 、删除podfile重新pod install等操作，操作以后依旧无效。将混淆flags去掉，项目恢复正常。

请问有何思路吗？

**Comment by Naville** [comment]
不支持Modules

**Comment by Sfvgtg** [comment]
> 不支持Modules

Hanabi注入的形式也不支持吗？只是走了混淆的pass，其他的不都是走的Apple Clang吗？有没有思路解决？

**Comment by Sfvgtg** [comment]
> 不支持Modules

直接使用Xcode编译没问题，开启bcf、cff、sub、strcry正常使用，混淆也有效果。
但是使用xcodebuild脚本运行就报错： fatal error: module 'WBRouter' not found。
请问这种情况有解决思路吗？感谢...

脚本内容(添加任意flags都会报错，同一错误)：
`
xcodebuild archive ARCHS="arm64" DEFINES_MODULE="YES" VALID_ARCHS="armv7s arm64" ONLY_ACTIVE_ARCH=NO DEPLOYMENT_POSTPROCESSING=YES \
    -workspace ${PROJECT_WORKSPACE} \
    -scheme ${SCHEME_NAME} \
    -configuration ${CONFIGURATION_TARGET} \
    -archivePath ${ARCHIVE_PATH} \
    -destination 'generic/platform=iOS'\
    GCC_OPTIMIZATION_LEVEL=0\
    OTHER_CFLAGS="-fno-objc-msgsend-selector-stubs -mllvm -enable-subobf"
`
