### ISSUE TITLE
clang-16: error: unknown argument: '-ivfsstatcache'

### ISSUE THREAD

**Issue by G5t4r** [61bcdefg/Hikari-LLVM15#80]
M1 Mac升级MacOS14.1.1 XCode15.0.1,使用llvm16.0.1rel分支编译项目报错
我在源码中的clang目录下的tool目录并没有找到clang/tools/clang-stat-cache，是因为缺少这个吗？

**Comment by Naville** [comment]
Apple的CAS实现还没提交给上流, 只能用Apple的fork

**Comment by G5t4r** [comment]
> Apple的CAS实现还没提交给上流, 只能用Apple的fork

是否让Xcode生成编译参数的时候，不让它指定ivfsstatcache？

**Comment by ta01st** [comment]
同问，这问题能解决吗？

**Comment by ta01st** [comment]
已解决，用xcodebuilder找到对应的key，设置为no就可以了

**Comment by 61bcdefg** [comment]
我这里测试只有在使用Xcode本身的toolchain使xcode才会传递这个参数，而使用自己构建的toolchain时xcode是不会传递这个参数的
