### ISSUE TITLE
Hikari is visual only

### ISSUE THREAD

**Issue by VanHoevenTR** [61bcdefg/Hikari-LLVM15#81]
I successfully integrated Hikari into NDK 26.1 but it is visual only, no obfuscation were applied to the .so file regardless where the flags are added in Android.mk or Appication.mk. Do you know what is going on?

**Comment by ARandomPerson7** [comment]
Generally, hikari does not support android ndk by default as Android ndk is using llvm14 and newer builds llvm 17, so you first need to port hikari to either llvm 17 or 14

**Comment by NewDwarf** [comment]
I did such integration with NDK 25c.

**Comment by Naville** [comment]
Or your code contains unsupported semantic and the obfuscator silently quit
