### ISSUE TITLE
求助：Theos编译tweak的时候怎么引用

### ISSUE THREAD

**Issue by Cregin** [61bcdefg/Hikari-LLVM15#82]
在Makefile指定TOOLCHAIN_DIR吗

CC = $(TOOLCHAIN_DIR)/usr/bin/clang
CXX = $(TOOLCHAIN_DIR)/usr/bin/clang++

然后在 CFLAGS 里添加对应的混淆指令？

张总，救救小白🤣

**Comment by G5t4r** [comment]
是的，你试试不就知道了

**Comment by Cregin** [comment]
@G5t4r 并没有生效，能给个Makefile的示例吗，谢谢

**Comment by Naville** [comment]
https://github.com/HikariObfuscator/TweakObfuscateDemo

?

**Comment by Cregin** [comment]
@Naville 感谢张总
