### ISSUE TITLE
支持最新的mac系统（14.2），支持M1芯片吗？

### ISSUE THREAD

**Issue by testpangbb** [61bcdefg/Hikari-LLVM15#84]
build阶段报错。是不是只支持inter系统

/Hikari/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cc:1216:1:  error: unknown type name '__sanitizer_XDR'; did you mean '__sanitizer_tm'?
CHECK_TYPE_SIZE(XDR);

Hikari/projects/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.h:1435:25: note: expanded from macro 'CHECK_TYPE_SIZE'
  COMPILER_CHECK(sizeof(__sanitizer_##TYPE) == sizeof(TYPE))

**Comment by chevesco** [comment]
llvm16 branch should've fixed this
