### ISSUE TITLE
how can I compile anti-hooking myself (solution of failing loading PreCompiled AntiHooking)

### ISSUE THREAD

**Issue by chevesco** [61bcdefg/Hikari-LLVM15#86]
`Failed To Link PreCompiled AntiHooking IR From:/var/root/Hikari/PrecompiledAntiHooking-aarch64-ios.bc`
ig the solution is just to build AH myself with `clang -S -emit-llvm -mllvm -enable-antihook -o output.bc` but it doesn't give any output.

**Comment by Naville** [comment]
clang -S -isysroot /PATH/TO/SYSROOT/ -emit-llvm input.c

**Comment by chevesco** [comment]
input.c should be AntiHooking.cpp (from llvm/lib/Transforms/Obfuscation) yep?

**Comment by Naville** [comment]
No, read the docs

**Comment by chevesco** [comment]
r u talking about Noctilucence? Otherwise that's unclear.

**Comment by Naville** [comment]
It's useless and just insert your own checks in source code.
The pass works by you writing your own check and handling code and load them into the program. You can do the same without using the obfuscator

**Comment by Naville** [comment]
As for the actual checking code, those are closed-source
