### ISSUE TITLE
Setting up Toolchain for AppStore

### ISSUE THREAD

**Issue by testpangbb** [61bcdefg/Hikari-LLVM15#87]
Setting up Toolchain for AppStore

① Use executables in Hikari.xctoolchain/usr/bin to override the executables in /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin, overwrite any existing files. Backup Original Content First In Case Something Went Wrong

② Alternatively, you could use Hikari's toolchain to build normally then remove ``DefaultToolchainOverrideInfo`` from the IPA's Info.plist

大神，我根据你的第二个方法，没有在info.plist里面找到DefaultToolchainOverrideInfo 字段，是否表示这一步我不需要进行处理了，还是说只能用第一个方法了，谢谢

I according to you the second method, without the info. The plist find DefaultToolchainOverrideInfo fields, whether said I don't need to be dealt with in this step, or can only use the first method. thanks

**Comment by Naville** [comment]
是的 没有就不用管
