### ISSUE TITLE
Xcode 14.2 / unknown argument: '-ivfsstatcache'

### ISSUE THREAD

**Issue by subu1979** [61bcdefg/Hikari-LLVM15#88]
How to solve this error

![Screenshot 2024-01-30 at 2 51 34 PM](https://github.com/61bcdefg/Hikari-LLVM15/assets/3286581/bd6fe175-692f-48d9-85b0-bccc7486083c)

**Comment by Naville** [comment]
Swift's version must match Xcode's version

**Comment by 61bcdefg** [comment]
I can't reproduce this issue
