### ISSUE TITLE
Theos编译tweak arm64e

### ISSUE THREAD

**Issue by wxhbts** [61bcdefg/Hikari-LLVM15#89]
xcode 版本：14.2
Hikari_Swift 版本：5.7.2
编译arm64 没有问题 编译arm64e报错
==> Compiling Tweak.x (arm64e)…
While building module 'Darwin' imported from /Users/liu/theos/Prefix.pch:18:
In file included from <module-includes>:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/signal.h:63:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/signal.h:146:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/machine/_mcontext.h:32:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/arm/_mcontext.h:36:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/mach/machine/_structs.h:33:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/mach/arm/_structs.h:179:10: fatal error: 'ptrauth.h' file not found
#include <ptrauth.h>
         ^~~~~~~~~~~
In file included from <built-in>:1:
/Users/liu/theos/Prefix.pch:18:10: fatal error: could not build module 'Darwin'
        #import <AvailabilityVersions.h>
         ~~~~~~~^
While building module 'Foundation' imported from Tweak.x:1:
While building module 'CoreFoundation' imported from /Applications/Xcode.a

**Comment by 61bcdefg** [comment]
我觉得这个问题跟这个项目大概是没有什么关系的

**Comment by ugly-soul** [comment]
> > 我觉得这个问题跟这个项目大概是没有什么关系的
> 
> 好的 感谢



> xcode 版本：14.2 Hikari_Swift 版本：5.7.2 编译arm64 没有问题 编译arm64e报错 ==> Compiling Tweak.x (arm64e)… While building module 'Darwin' imported from /Users/liu/theos/Prefix.pch:18: In file included from :21: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/signal.h:63: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/sys/signal.h:146: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/machine/_mcontext.h:32: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/arm/_mcontext.h:36: In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/mach/machine/_structs.h:33: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk/usr/include/mach/arm/_structs.h:179:10: fatal error: 'ptrauth.h' file not found #include <ptrauth.h> ^~~~~~~~~~~ In file included from :1: /Users/liu/theos/Prefix.pch:18:10: fatal error: could not build module 'Darwin' #import <AvailabilityVersions.h> ~~~~~~~^ While building module 'Foundation' imported from Tweak.x:1: While building module 'CoreFoundation' imported from /Applications/Xcode.a

不好意思，打扰一下。请问你最后是舍弃了arm64e的编译了嘛？我目前编译结果和你一样的问题
