### ISSUE TITLE
No installation??

### ISSUE THREAD

**Issue by busmanl30** [61bcdefg/Hikari-LLVM15#90]
I don't know if it is just me but i dont see a release for this fork? I wanna upgrade from the Old Hikari since that one is very old and doesn't support arm64e

**Comment by Naville** [comment]
Have you considered building yourself?

**Comment by 61bcdefg** [comment]
You need to build it by yourself

**Comment by busmanl30** [comment]
Disregard, didnt see the branches, i do however got an error rightg at the end.
