### ISSUE TITLE
Original LLVM compiles fine vs Hikari, using same commands

### ISSUE THREAD

**Issue by busmanl30** [61bcdefg/Hikari-LLVM15#93]
Yesterday it was claimed that there was something wrong with my end with Compiling hikari, this time i even tried 5.8 and LLVM16 and not only used same commands, i compiled the exact original version with and without clang PERFECTLY FINE, Only errors i did were have were because of memory but that was an easy fix just redo the compilation and it work. I think something was messed up on releases because this doesnt make sense

**Comment by 61bcdefg** [comment]
I don't know why you want to build this project in WSL. The project itself was a small toy and was not expected to be built i WSL. Anyway, I have no interest in whether this project can be built in WSL, if you want to build it in WSL, you can try to fix this problem yourself, please don't just create a new issue for this

**Comment by busmanl30** [comment]
I have no other choice to build in WSL, i dont own a mac and theres no precompiled version for this.

**Comment by kbd228** [comment]
stfu nigger

**Comment by kbd228** [comment]
ching chong dirty ass
