### ISSUE TITLE
Hanabi Build for Xcode 15.2 missing?

### ISSUE THREAD

**Issue by malhaar** [61bcdefg/Hikari-LLVM15#94]
hey i cant find hanabi build for xcode 15 .. can you please reupload?

**Comment by 61bcdefg** [comment]
Swift was fully broken on Hanabi for xcode15, so I didn't upload it

**Comment by malhaar** [comment]
i tested old build on latest xcode, just did not inject in swift-frontend and its working fine on objc builds. also any plans for fixing swift-fontend?

**Comment by 61bcdefg** [comment]
Fixing it won't be easy, I'm not going to do

**Comment by malhaar** [comment]
alright ..

**Comment by Naville** [comment]
I don't understand the love with injection-based solutions. Back in the older days building Swift was a giant p in the a. It's way much simpler now

**Comment by malhaar** [comment]
well i can talk for myself not others .. it makes easy to use with xcode and lots still use xcode. Most of people dont know manual setups of compilers .. if i get some tutorial to use it without xcode i will be more than happy to say bye bye to xcode ...

**Comment by Naville** [comment]
Unless you require building for aarch64e (which has other workarounds), using a standalone toolchain works equally good

**Comment by malhaar** [comment]
@Naville can you please link me to any tutorial for beginners?

**Comment by Naville** [comment]
[Right in the README](https://github.com/61bcdefg/Hikari-Swift)

**Comment by 61bcdefg** [comment]
> Unless you require building for aarch64e (which has other workarounds), using a standalone toolchain works equally good

Actually the workaround for arm64e is unable to work properly like hanabi, if the source code contain objc class, the springboard will crash.

Apple doesn't seem to be pushing the latest arm64e abi implementation into their llvm fork

**Comment by Naville** [comment]
> > Unless you require building for aarch64e (which has other workarounds), using a standalone toolchain works equally good
> 
> Actually the workaround for arm64e is unable to work properly like hanabi, if the source code contain objc class, the springboard will crash.
> 
> Apple doesn't seem to be pushing the latest arm64e abi implementation into their llvm fork

There was a script released by theos developers that patchs the arch tag in MachO to pretend to be the new arm64e abi.
Which is stupid, indeed, but works reasonably well in practice

**Comment by malhaar** [comment]
yeah.. that could work.. @61bcdefg what do you think?

**Comment by 61bcdefg** [comment]
I missed something. For some unknown reason, even though I used apple's fork of llvm, the mach-o was still marked 0x80000002, which led oldabi to think it didn't need to be patched. Also, if I modify the section name, oldabi will not work properly because it assumes that all hikari strings are in the section named __data

**Comment by 61bcdefg** [comment]
Other than that, I've heard it doesn't seem to work with swift (unverified).

**Comment by 61bcdefg** [comment]
A unfortunate news: On Xcode 15.3, clang is also fully broken if hanabi is used, and seems impossible to fix(crash at the backend)

**Comment by malhaar** [comment]
Damn there goes a good project .. !

**Comment by Sfvgtg** [comment]
抱歉打扰了，看到了关于Hanabi方案该问题的描述，包括之前用的Swift的独立工具链方案，都或多或少遇到一些问题。是否能添加一下容错机制或者改一下流程？针对编译器开发我是小白，请问以下这种思路是否有可行性？
做一个统筹的流程控制器作为入口，用来协调切换系统clang跟自己编译的混淆工具，产生IR以及后续的IR到后端的过程都交由系统clang来做，自己的混淆工具只介入到IR的混淆中，当混淆工具报错时切换到系统clang去重新编译一次，
