### ISSUE TITLE
Hanabi

### ISSUE THREAD

**Issue by Sfvgtg** [61bcdefg/Hikari-LLVM15#96]
> Swift混淆支持
> 由于Xcode的LLVM相比原版LLVM有大量闭源改动，Hanabi在Xcode 15起已无法编译Swift。

打扰了，hanabi不针对swift-frontend注入可用吗？还是编译阶段就无法通过...不针对Swift混淆是否有方案？

**Comment by 61bcdefg** [comment]
xcode15.0-15.2是可以正常混淆c/c++/objective-c/objective-c++的，你可以自己构建hanabi

**Comment by Sfvgtg** [comment]
请问Xcode15.3可以吗？

**Comment by Naville** [comment]
<img width="608" alt="image" src="https://github.com/61bcdefg/Hikari-LLVM15/assets/5205699/85628496-bcf6-4cf7-b744-3b0a3c9b2074">
